# Generated by Django 5.0 on 2023-12-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('security', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
