# Generated by Django 5.0 on 2023-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=17)),
                ('expiration_date', models.CharField(max_length=50)),
                ('cvv_code', models.CharField(max_length=10)),
                ('card_holder_name', models.CharField(max_length=25)),
                ('amount', models.CharField(max_length=25)),
            ],
        ),
    ]
