# Generated by Django 5.0 on 2023-12-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_order_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='dish_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
