# Generated by Django 5.0 on 2023-12-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_order_description_order_dish_name_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dish_name',
            field=models.CharField(max_length=255),
        ),
    ]
