# Generated by Django 5.0 on 2023-12-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_remove_order_dish_details_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_data',
            name='email',
            field=models.CharField(max_length=60),
        ),
    ]
