# Generated by Django 5.0 on 2023-12-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0016_alter_registration_data_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_data',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
