# Generated by Django 5.0 on 2023-12-19 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0017_alter_registration_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
