# Generated by Django 5.0 on 2023-12-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0019_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expiration_date',
        ),
    ]
