# Generated by Django 5.0 on 2023-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0020_remove_order_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(verbose_name='Order Date and Time'),
        ),
    ]
