# Generated by Django 5.0 on 2023-12-20 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0021_alter_order_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date and Time'),
        ),
    ]
